services:
  pgsql:
    image: postgres:18-alpine
    restart: always
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-velaris}
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
