services:
  pgsql:
    image: postgres:18-alpine
    restart: always
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_DB: ${DB_NAME:-velaris}
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
