@baseUrl = http://localhost:8000
@contentType = application/json

POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
    "email": "bob@aol.com",
    "password": "password"
}

###

POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
    "name": "Bob Johnson",
    "email": "bob@aol.com",
    "password": "password",
    "password_confirmation": "password"
}

###

POST {{baseUrl}}/boards
Content-Type: {{contentType}}

{
    "name": "lorem",
    "description": "lorem ipsum dolor"
}